fix No overload matches this call
error message:

vue-screen:   ● Test suite failed to run
vue-screen:     __tests__/plugin.ts:30:5 - error TS2769: No overload matches this call.
vue-screen:       Overload 1 of 2, '(plugin: Plugin<[options?: VueScreenConfig]>, options?: VueScreenConfig): App<Element>', gave the following error.
vue-screen:         Argument of type '{ ssr: { width: number; height: number; }; }' is not assignable to parameter of type 'VueScreenConfig'.
vue-screen:           Property 'grid' is missing in type '{ ssr: { width: number; height: number; }; }' but required in type 'VueScreenConfigObject'.
vue-screen:       Overload 2 of 2, '(plugin: Plugin<[options?: VueScreenConfig]>, options: [options?: VueScreenConfig]): App<Element>', gave the following error.
vue-screen:         Argument of type '{ ssr: { width: number; height: number; }; }' is not assignable to parameter of type '[options?: VueScreenConfig]'.
vue-screen:           Object literal may only specify known properties, and 'ssr' does not exist in type '[options?: VueScreenConfig]'.
vue-screen:      30     app.use({install}, {